### ISSUE TITLE
Option -c(--scan-only) fails without option -o (--output-dump) specified

### ISSUE THREAD

**Issue by beatcracker** [jasperlee108/svndumpfilterIN#6]
**Example:**
```shell
pypy.exe svndumpfilter.py --scan-only dump.svn include "nested/path"
Starting to filter dumpfile : dump.svn
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "svndumpfilter.py", line 805, in <module>
    main()
  File "svndumpfilter.py", line 800, in main
    parse_dump(input_dump, opt.output_dump, matches, include, opt)
  File "svndumpfilter.py", line 685, in parse_dump
    clean_up(output_dump)
  File "svndumpfilter.py", line 552, in clean_up
    os.remove(filename)
TypeError: expected string, got NoneType object
```
**Workaround:** specify any file or null device with option ```-o```

Note, that alias ```--output-dump``` doesn't work in this case. If specified, the file ```utput-dump``` is created in current directory.

**Example (Windows):**
```shell
pypy.exe svndumpfilter.py --scan-only dump.svn include "nested/path" -o NUL
```

**Comment by freeamac** [comment]
Again believe your changes addressed this. Thanks!
